### ISSUE TITLE
课后作业提交会报错

### ISSUE THREAD

**Issue by F-loat** [lskzsy/EryaKiller#1]
报错内容：
``` PowerShell
Traceback (most recent call last):
  File ".\Eryakill-3.0.py", line 1281, in <module>
    UserInterface()
  File ".\Eryakill-3.0.py", line 116, in UserInterface
    GoErya()
  File ".\Eryakill-3.0.py", line 100, in GoErya
    EryaKiller()
  File ".\Eryakill-3.0.py", line 1272, in EryaKiller
    score = GetScoreArg(cid, clazzid, courseid, jobId, workId, utenc ,enc)
  File ".\Eryakill-3.0.py", line 561, in GetScoreArg
    return score[0]
IndexError: list index out of range
```

**Comment by F-loat** [comment]
提交时会报RRORForbidden

**Comment by lskzsy** [comment]
暂时不支持多选题

**Comment by F-loat** [comment]
嗯，这个完成度已经很高了，希望能继续完善下😂
